export const PERMISSIONS = {
  DASHBOARD: 'dashboard',
  USERS: 'users',
  KYC: 'kyc',
  JOBS: 'jobs',
  WALLET: 'wallet',
  DISPUTES: 'disputes',
  SUPPORT: 'support',
  NOTIFICATIONS: 'notifications',
  CONTENT: 'content',
  STAFF: 'staff',
  CHAT: 'chat',
  SETTINGS: 'settings',
  SECURITY: 'security'
};

export const ROLE_PERMISSIONS = {
  super: [PERMISSIONS.DASHBOARD, PERMISSIONS.USERS, PERMISSIONS.KYC, PERMISSIONS.JOBS, 
          PERMISSIONS.WALLET, PERMISSIONS.DISPUTES, PERMISSIONS.SUPPORT, 
          PERMISSIONS.NOTIFICATIONS, PERMISSIONS.CONTENT, PERMISSIONS.STAFF, 
          PERMISSIONS.CHAT, PERMISSIONS.SETTINGS, PERMISSIONS.SECURITY],
  support: [PERMISSIONS.DASHBOARD, PERMISSIONS.USERS, PERMISSIONS.SUPPORT, PERMISSIONS.CHAT],
  compliance: [PERMISSIONS.DASHBOARD, PERMISSIONS.KYC, PERMISSIONS.DISPUTES, PERMISSIONS.SETTINGS],
  finance: [PERMISSIONS.DASHBOARD, PERMISSIONS.WALLET, PERMISSIONS.ANALYTICS, PERMISSIONS.SETTINGS]
};

export default PERMISSIONS;
